#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

foamListTimes -rm
rm -r postProcessing*
rm -r 0
cp -r 0.orig 0
blockMesh

foamDictionary -entry "divSchemes/div(phi,T)" -set "Gauss linear" \
    system/fvSchemes
explicitRK4scalarTransportFoam
postProcess -func graphCell -latestTime
mv postProcessing postProcessing-CD
foamListTimes -rm

foamDictionary -entry "divSchemes/div(phi,T)" -set "Gauss upwind" \
    system/fvSchemes
explicitRK4scalarTransportFoam
postProcess -func graphCell -latestTime
mv postProcessing postProcessing-UD
foamListTimes -rm

foamDictionary -entry "divSchemes/div(phi,T)" -set "Gauss blended 0.9" \
    system/fvSchemes
explicitRK4scalarTransportFoam
postProcess -func graphCell -latestTime
mv postProcessing postProcessing-BD
foamListTimes -rm

foamDictionary -entry "divSchemes/div(phi,T)" \
    -set "GaussScaleSelective Gauss linear orthogonal 2.0 upwind linear" \
    system/fvSchemes
explicitRK4scalarTransportFoam
postProcess -func graphCell -latestTime
mv postProcessing postProcessing-SSD
foamListTimes -rm

#------------------------------------------------------------------------------
