#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

wclean solvers/basic/explicitRK4scalarTransportFoam
wclean solvers/basic/SSDscalarTransportFoam/SSDexplicitRK4ScalarTransportFoam
wclean solvers/basic/SSDscalarTransportFoam/SSDimplicitScalarTransportFoam
